# Introduction to Python

### python Variable

In [1]:
x = 1
print(x)

1


In [2]:
y = 2


In [3]:
print(y)

2


In [5]:
a,b = (2,4)

In [6]:
print(a)

2


In [7]:
print(b)

4


In [9]:
w,z,p = (1,2,3)

### Types of data 

* integer
* Boolean
* String 
* Float
* Object/Dictionary
* Array/ List 

In [19]:
y = 2.1
print(y)

2.1


In [20]:
type(y)

float

In [22]:
x = 'Name'
print(x)

Name


In [23]:
type(x)

str

In [25]:
a = True   # Fales 
print(a)

True


In [26]:
type(a)

bool

In [27]:
a = 1
b = 2.1

In [28]:
a + b

3.1

In [29]:
print(a)

1


In [30]:
a = 5


In [31]:
print(a)

5


In [32]:
a+5

10

In [33]:
a/b

2.380952380952381

In [35]:
int(14/3)

4

In [36]:
fo = 3
type(fo)

int

In [40]:
fo = float(fo)

In [41]:
type(fo)

float

In [43]:
# 5**2

### Comparison Operator

In [47]:
10 == 20/2

True

In [50]:
10 != 10

False

In [54]:
10 > 10

False

In [ ]:
> , < , >= , <= , != 

In [57]:
5 is 5
 or 5 == 5

<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\Dell\AppData\Local\Temp/ipykernel_840/1783323536.py:1: SyntaxWarning: "is" with a literal. Did you mean "=="?
  5 is 5


True

In [63]:
# 5 ! = 6
5 is not 6


<>:2: SyntaxWarning: "is not" with a literal. Did you mean "!="?
<>:2: SyntaxWarning: "is not" with a literal. Did you mean "!="?
C:\Users\Dell\AppData\Local\Temp/ipykernel_840/255014600.py:2: SyntaxWarning: "is not" with a literal. Did you mean "!="?
  5 is not 6


True

### Conditional statement

In [65]:
a = 5
if a == 5:
    print("Yes!!! ")
else:
    print("Oh No!!!")
    
    

Yes!!! 


In [68]:
a =3
if a == 5:
    print("Yes!!! ")
elif a == 4:
    print("its Four")
else:
    print("Oh No!!!")
    

Oh No!!!


### Function 

In [72]:
def squre_func(a):
    print(a**3)



In [73]:
squre_func(5)

125


In [74]:
def power_machine(base_value,power_value):
    return base_value**power_value

In [75]:
power_machine(2,3)

8

In [76]:
def comparison_d(val):
    if val == 5:
        print("Yes!!! ")
    elif val == 4:
        print("its Four")
    else:
        print("Oh No!!!")
        

In [79]:
comparison_d(8)

Oh No!!!


In [81]:
a = 2
type(a)

int

In [82]:
b = float(a)

In [83]:
b

2.0

In [84]:
type(b)

float

In [85]:
c = str(b)

In [86]:
c

'2.0'

In [ ]:
max , min , abs , round , sum , pow, len 

In [87]:
len(c)

3

### List

In [94]:
user = ['Amin','Mobin','korim']

In [95]:
user

['Amin', 'Mobin', 'korim']

In [96]:
type(user)

list

In [97]:
user[1]

'Mobin'

In [98]:
user[2]

'korim'

In [99]:
user[0]

'Amin'

In [101]:
user[-2]

'Mobin'

In [102]:
user

['Amin', 'Mobin', 'korim']

In [103]:
user.append('Rohit')

In [104]:
user

['Amin', 'Mobin', 'korim', 'Rohit']

In [106]:
user.extend(['Jhon','Lorem','Ipsum','Doe'])

In [107]:
user

['Amin', 'Mobin', 'korim', 'Rohit', 'Jhon', 'Lorem', 'Ipsum', 'Doe']

In [108]:
len(user)

8

In [113]:
# user [start:end:jump]

user[1:-1:3]

['Mobin', 'Jhon']

In [114]:
user[:2]

['Amin', 'Mobin']

In [115]:
user[3:]

['Rohit', 'Jhon', 'Lorem', 'Ipsum', 'Doe']

In [116]:
user[1::3]

['Mobin', 'Jhon', 'Doe']

### Touple


In [1]:
list_1 = [1,2,4,5]

In [2]:
list_1

[1, 2, 4, 5]

In [4]:
list_1[2] = 9

In [5]:
list_1

[1, 2, 9, 5]

In [6]:
list_1.remove(9)

In [7]:
list_1

[1, 2, 5]

In [8]:
lis_2 = [ 4,7,9,1,0,2]

In [9]:
lis_2

[4, 7, 9, 1, 0, 2]

In [16]:
lis_2.sort(reverse= True)

In [17]:
lis_2

[9, 7, 4, 2, 1, 0]

In [18]:
a = 'Rohim'

In [19]:
a

'Rohim'

In [23]:
a[1::2]

'oi'

In [30]:
number = '2346513'

In [31]:
number[2]

'4'

In [32]:
a

'Rohim'

In [35]:
a[2] = 'Y'

TypeError: 'str' object does not support item assignment

### Dictionary

In [38]:
dict = {
    'v1' : 'Cat',
    'v2' : 'Dog',
    'v3' : 'bilai'
}

dict

{'v1': 'Cat', 'v2': 'Dog', 'v3': 'bilai'}

In [42]:
dict['v3']

'bilai'

In [45]:
dict['v4']='Tiger' 

In [46]:
dict

{'v1': 'Cat', 'v2': 'Dog', 'v3': 'bilai', 'v4': 'Tiger'}

In [47]:
dict['v3'] = 'Kukur'

In [48]:
dict

{'v1': 'Cat', 'v2': 'Dog', 'v3': 'Kukur', 'v4': 'Tiger'}

In [59]:
peoples = {
   '01':{'name' : "Rahim",
    'age':34,
    'address':'Dhaka',
    'gender': 'M' },
  '02':{'name' : "karim",
    'age':24,
    'address':'Raj',
    'gender': 'M' }
}

In [60]:
peoples['02']['address']

'Raj'

### Loop


In [61]:
numbers = [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

In [62]:
numbers

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [71]:

for n in numbers:
    print(n)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20


In [81]:
numbers_2 = list(range(0,31))

In [82]:
numbers_2

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30]

In [83]:
for i in numbers_2:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30


In [87]:
x =  0 

while x <= 20:
    print(x,end=" ")
    x=x+2

0 2 4 6 8 10 12 14 16 18 20 

In [86]:
x

22

In [88]:
for n in range(10):
    print(2**n)

1
2
4
8
16
32
64
128
256
512


In [91]:
for x in range(21):
    if x%2 == 0:
        print(x)
    else:
        print('Odd')

0
Odd
2
Odd
4
Odd
6
Odd
8
Odd
10
Odd
12
Odd
14
Odd
16
Odd
18
Odd
20


In [92]:
name = 'Rahim'
for x in name:
    print(x)

R
a
h
i
m


In [93]:
import math

In [94]:
math.sqrt(4)

2.0

In [95]:
help(math)

Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return the inverse hyperbolic tangent of x.
    
    ceil(x, /)
        Return the ceiling of x as an Integral.
      

### Numpy & Pandas

In [96]:
import numpy as np

In [97]:
np.__version__


'1.20.3'

In [100]:
s = 2
s

2

In [103]:
# vector 

v = np.array([4,1,-9])
print(v)

[ 4  1 -9]


In [104]:
type(v)

numpy.ndarray

In [105]:
# Matrix

m = np.array([
    [5,6,8],
    [1,2,5],
    [6,1,2]
])

In [106]:
m

array([[5, 6, 8],
       [1, 2, 5],
       [6, 1, 2]])

In [107]:
type(m)

numpy.ndarray

In [109]:
m.shape

(3, 3)

In [110]:
v.shape

(3,)

In [115]:
v

array([ 4,  1, -9])

In [116]:
v1 = v.reshape(3,1)
v1

array([[ 4],
       [ 1],
       [-9]])

In [117]:
v1.shape

(3, 1)

In [118]:
m2 = np.array([
    [8,2,1,3],
    [4,2,9,8]
])
m2

array([[8, 2, 1, 3],
       [4, 2, 9, 8]])

In [119]:
m2.shape

(2, 4)

In [121]:
m2.reshape(4,2)

array([[8, 2],
       [1, 3],
       [4, 2],
       [9, 8]])

In [122]:
mat1 = np.array([
    [3,4,7],
    [4,5,6],
    [2,1,6]
])

mat2 = np.array([
    [43,2,-1],
    [6,5,-3],
    [2,3,-1]
])

In [123]:
mat1

array([[3, 4, 7],
       [4, 5, 6],
       [2, 1, 6]])

In [124]:
mat2

array([[43,  2, -1],
       [ 6,  5, -3],
       [ 2,  3, -1]])

In [125]:
ten = np.array([
    mat1,
    mat2
])

In [126]:
ten

array([[[ 3,  4,  7],
        [ 4,  5,  6],
        [ 2,  1,  6]],

       [[43,  2, -1],
        [ 6,  5, -3],
        [ 2,  3, -1]]])

In [127]:
ten.shape

(2, 3, 3)

In [130]:
ten2 = np.array([
    [
        [32,53,21],
        [45,21,9]
    
    ],
    [
        [54,32,11],
        [87,-45,34]
       
    ],
    [
        [543,21,-98],
        [43,12,-87]
      
    ]
])

In [131]:
ten2.shape

(3, 2, 3)